[package]
name = "scripts_omics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpu-time = "1.0.0"
csv = "1.2.1"
statistical = "1.0.0"
stats = "0.0.1"
