[package]
name = "scripts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "1.1.0"
bio-seq = "0.9.0"
bio-types = "0.13.0"
cpu-time = "1.0.0"
csv = "1.2.1"
entrez-rs = "0.1.4"
seq_io = "0.3.1"
